server:
  port: 8761

eureka:
  security:
    basic:
      enabled: false
  instance:
    prefer-ip-address: true
#    ip-address: 192.168.5.102
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/